### PR TITLE
Add documentation about React Native support

### PR DESCRIPTION
**Pull request by mitjade**
This is just initial draft.

Please comment what is missing, not well explained or misleading.

@vlasenko Please add some `webpack`, `expo` and `haul` explanation.

@mairh Please add your comments as well, since you already started playing with this and can provide valuable info of what else is not clear, for someone who wants to start with this.

### CODE REVIEW

**Comment by vlasenko** [comment]
In the part about Haul, it is misleading. We don't use Haul for React Native packaging. We use Webpack for React Native packaging with the help partly from Haul parts, partly from React Native parts, partly from other packages.

**Comment by mitjade** [comment]
Could you please rewrite that part, since I am not familiar how exactly that works.

**Comment by vlasenko** [comment]
Sure

**Comment by mitjade** [comment]
Maybe also add some mobile pictures to highlight that part as well?

**Comment by vlasenko** [comment]
@mitjade Yes, it would be great to replace the video we currently have in a gif to give a feeling how working with the kit looks like

**Comment by vlasenko** [comment]
I think we can integrate this PR in its current state

**Comment by mairh** [comment]
Perhaps add a note to enable command line tools in `xcode` otherwise the simulator won't open. Whenever there is a fresh `xcode` install the command line tool dropdopwn is empty so you need to manually select the version from the dropdown list in order to make the emulator work.

screen shot 2017-06-07 at 11 39 36

**Comment by mitjade** [comment]
Yes, thx. Forgot about that, since it's been a while since I've done that.

**Comment by mitjade** [comment]
@mairh  Did you also need to install Watchman. I know I did when playing with react native, but am not sure if it is required here?

**Comment by mairh** [comment]
Yes, watchman is needed for hot reload the changes to your device. It should be installed globally

**Comment by vlasenko** [comment]
At the moment we don't support Hot Reload for React Native. Only Live Reload. Live Reload - fully reloads app on device when change is detected. Hot reload is other thing - it tries to hot patch the code of running application on the device without fully reloading it. We are going to support it later, its quite a big effort, but Live Reload should be enough though for practical needs with fast incremental builds and we will do them faster then now soon, I'm working on it

**Comment by mitjade** [comment]
So Watchman is then currently not needed?

**Comment by mitjade** [comment]
So I guess this is good enough for starters and we can improve upon this later on.

If you both agree, will then merge this PR?

**Comment by vlasenko** [comment]
Yes, I agree

**Comment by mairh** [comment]
👍

**Pull request merged**
