### PR TITLE
update graphql-auth

### PR DESCRIPTION
**Pull request by mitjade**
Second try.

### CODE REVIEW

**Comment by vlasenko** [comment]
`graphql-auth@0.2.1` is packaged incorrectly, it doesn't have `build` folder

**Comment by mitjade** [comment]
@vlasenko Yes. I contacted package owner and notified him. He said he will fix it shortly, so I just gave it another try if anything has changed. Will update this PR when a new version will be ready.

**Comment by mitjade** [comment]
@vlasenko Seems to be ok now.

**Comment by vlasenko** [comment]
ok, thanks

**Pull request merged**
