### PR TITLE
Made changes to docs/FAQ and docs/Configuration

### PR DESCRIPTION
**Pull request by Minus0149**
As shown in issue #1113 "Docs refer to user.js which appears to be in auth.js and has been somewhat restructured" changed the document according to the instructions given as the original was pointing towards wrong file.

### CODE REVIEW

**Comment by larixer** [comment]
Thanks, but why do you add Scala doc in this PR?

**Comment by Minus0149** [comment]
@larixer I did not.
image
as you could see in the image it was added by AndSviat.

**Comment by larixer** [comment]
I know, but the question is why it is in your PR?
image

**Comment by Minus0149** [comment]
@larixer I created a pull request for just those 2 files namely faq and configuration. I don't understand how it got included. My deepest apologies for the confusion caused.

**Comment by larixer** [comment]
@Minus0149 You have forked from `docs` branch, that branch was a temporarily and now it is heavily outdated, all the development happens on `master`, if you want correct docs, please do it by forking `master` instead and creating PR after that.

**Comment by Minus0149** [comment]
@larixer Done you could check #1235 PR.

**Pull request closed without merging**
