### PR TITLE
active navbar link

### PR DESCRIPTION
**Pull request by mitjade**
- update bootstrap
- make nav bar link active

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko Any objections?

**Comment by vlasenko** [comment]
@mitjade Looks good to me, thanks Mitja

**Comment by mairh** [comment]
Please update cli template as well

**Comment by vlasenko** [comment]
Merging this one has added two new yarn warnings, I think these deps should be added:
```
warning "bootstrap@4.0.0-beta" has unmet peer dependency "jquery@>=3.0.0".
warning "bootstrap@4.0.0-beta" has unmet peer dependency "popper.js@^1.11.0"
```

**Comment by mairh** [comment]
@mitjade Is there any way to keep the parent link active when going into sub-routes?

Check the Heroku demo

https://apollo-universal-starter-kit.herokuapp.com/post/20

The posts link is not active anymore

**Comment by mitjade** [comment]
@vlasenko These are optional dependencies that we do not use currently, so I would not add them.

@mairh The problem is that `Posts` is not a sub-route of `Post`, so I do not know how to achieve this?
I would lease it as is for now, if I figure this out will add an example later.

**Comment by mairh** [comment]
Yeah, I am aware of the reason why it is not working at the moment. I was more interested in finding a solution. Let me see if I can think of a way to achieve that.

**Pull request merged**
