### PR TITLE
added APP_DIR to the readme section on docker

### PR DESCRIPTION
**Pull request by mkondel**
Tried to start in docker with 
```bash
docker-compose up
```
Got this error:
```bash
WARNING: The APP_DIR variable is not set. Defaulting to a blank string.
Creating apollo_universal_starter ... error

ERROR: for apollo_universal_starter  Cannot create container for service node: invalid volume specification: '/foobardrive/apollo-universal-starter-kit:.:rw': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute

ERROR: for node  Cannot create container for service node: invalid volume specification: '/foobardrive/apollo-universal-starter-kit:.:rw': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

```
The simplest thing to do was to try with the full path to the local dir like this:
```bash
APP_DIR=`pwd` docker-compose up
```
Tested on my machine, and now I can access the app through http://localhost:3000/

### CODE REVIEW

**Comment by vlasenko** [comment]
@mkondel Thanks for reporting this issue. I think this won't work under Windows. We need to find cross-platform solution

**Comment by mkondel** [comment]
Is there docker-compose for Windows?

**Comment by vlasenko** [comment]
@mkondel Yes:
https://docs.docker.com/compose/install/

**Comment by vlasenko** [comment]
@mkondel I think we should add `.env` file into the root especially for the docker-compose with only this line:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/.env#L2
And remove the corresponding lines from `packages/server/.env`.
You have faced the bug with docker, because we have moved `.env` from the root of the project into `package/server/.env` and docker files are depending on `APP_DIR` env var defined in `.env`

**Comment by mkondel** [comment]
I just tried making a new file in the project root dir '.env' with only this in it:
```
APP_DIR=/usr/src/app
```
When I run docker-compose there is an error about permissions to the above folder:
```
# docker-compose up

Starting eb329e1a51c2_apollo_universal_starter ... done
Attaching to eb329e1a51c2_apollo_universal_starter
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info @expo/traveling-fastlane-darwin@1.2.5: The platform "linux" is incompatible with this module.
info "@expo/traveling-fastlane-darwin@1.2.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > tslint-plugin-prettier@1.3.0" has unmet peer dependency "prettier@^1.4.0".
warning "tslint-plugin-prettier > eslint-plugin-prettier@2.6.0" has unmet peer dependency "prettier@>= 0.11.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client@1.0.0" has unmet peer dependency "@expo/vector-icons@^6.2.1".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client@1.0.0" has unmet peer dependency "antd-mobile@^2.1.2".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client@1.0.0" has unmet peer dependency "native-base@^2.3.5".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client@1.0.0" has unmet peer dependency "react-native@https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client@1.0.0" has unmet peer dependency "react-navigation@^1.0.0-beta.21".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > bootstrap@4.0.0-beta.2" has unmet peer dependency "jquery@1.9.1 - 3".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > heroku-babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > mocha-webpack@0.7.0" has incorrect peer dependency "mocha@^2.4.5 || ^3.0.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > native-base@2.3.7" has unmet peer dependency "react@>=16.0.0-alpha.3".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > react-navigation@1.0.0-beta.27" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > haul@1.0.0-beta.11" has incorrect peer dependency "babel-preset-react-native@^2.0.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > haul@1.0.0-beta.11" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > react-native@0.52.0" has unmet peer dependency "react@16.2.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > client > antd > rc-editor-mention@1.1.4" has unmet peer dependency "immutable@~3.7.4".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > antd-mobile > react-native-collapsible@0.9.0" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > antd-mobile > react-native-drawer-layout@1.3.2" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > lottie-react-native@2.3.2" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-branch@2.0.0-beta.3" has unmet peer dependency "react@>=15.4.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-gesture-handler@1.0.0-alpha.39" has unmet peer dependency "react@> 15.0.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-maps@0.19.0" has unmet peer dependency "react@16.0.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-maps@0.19.0" has incorrect peer dependency "react-native@0.51.0".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-maps@0.19.0" has unmet peer dependency "prop-types@^15.5.10".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > native-base > native-base-shoutem-theme@0.2.2" has unmet peer dependency "react@>=16.0.0-alpha.3".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > react-navigation > react-native-tab-view@0.0.74" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > xdl > glob-promise@3.3.0" has unmet peer dependency "glob@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-svg@5.5.1" has unmet peer dependency "react@*".
warning "workspace-aggregator-e52c2c28-16df-4e69-b457-d41c941ff925 > mobile > expo > react-native-svg@5.5.1" has unmet peer dependency "prop-types@^15.5.8".
error An unexpected error occurred: "EACCES: permission denied, mkdir '/usr/src/app/node_modules/abab'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
When I try using `pwd`, there is another error:
```
docker-compose up
Recreating eb329e1a51c2_apollo_universal_starter ... error

ERROR: for eb329e1a51c2_apollo_universal_starter  Cannot create container for service node: the working directory '`pwd`' is invalid, it needs to be an absolute path

ERROR: for node  Cannot create container for service node: the working directory '`pwd`' is invalid, it needs to be an absolute path
ERROR: Encountered errors while bringing up the project.
```
So it seems not possible to use pwd in the .env file. Any ideas?

**Comment by vlasenko** [comment]
@mkondel Have you tried `docker-compose up --build` ?

**Comment by vlasenko** [comment]
@mkondel `.env` in `.gitignore` is for a reason, we don't want users of the starter kit commited their credentials, that usually go to `.env` into git/github by accident. I wonder can you commit `.env` without adding it to `.gitgnore`, using the way like this:
https://stackoverflow.com/questions/8006393/force-add-despite-the-gitignore-file

**Comment by vlasenko** [comment]
@mkondel Or maybe you can just add `.env` to `.gitignore` using another commit now

**Comment by mkondel** [comment]
With ```docker-compose up --build``` it works and starts the server on localhost:3000.  I will add .env back into .gitignore. So in the end, there will still be a .env file with that one line in this repo, but any changes to it will never be picked up?

**Comment by vlasenko** [comment]
Thanks! Merged

Yes, any changes .env should not be normally picked

**Pull request merged**
