### PR TITLE
Add Material UI integration for React client

### PR DESCRIPTION
**Pull request by BaloPhilip**
This PR contains Material UI toolkit for React client.
Issue #751

### CODE REVIEW

**Comment by basicBrogrammer** [comment]
Has this been added?

**Comment by larixer** [comment]
@basicBrogrammer Nope

**Comment by basicBrogrammer** [comment]
@larixer any reason ? looks like @BaloPhilip put in a lot of work.

**Comment by larixer** [comment]
@basicBrogrammer The reason is very simple, the PR is unfinished and the work has stalled, so... whenever the work resumes on the PR and it will be finished, it will be merged.

**Comment by basicBrogrammer** [comment]
Cool deal didn't realize that

**Pull request closed without merging**
