### PR TITLE
Upgrade to Apollo v2

### PR DESCRIPTION
**Pull request by vlasenko**
This is a work in progress

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko I see you managed to get Apollo v2 working. Any thoughts?

What I can tell from the code, not yet working: persistent queries, batching, middleware (auth not working).

**Comment by vlasenko** [comment]
@mitjade UI tests not working, Apollo logging not working. I think I will be able to fix everything soon, except persistent queries, since the problem is `persistgraphql` does not support Apollo v2 yet.

**Comment by mitjade** [comment]
@vlasenko Great news!

**Comment by vlasenko** [comment]
Travis stuck on the old commit, going to recreate PR

**Comment by mitjade** [comment]
@vlasenko I see you managed to get all but `persistgraphql ` working on Apollo v2. I also tested the `client.resetStore()` problem and the `loading` issue seems to be gone in v2, but store still does not get reset as mentioned here: https://github.com/apollographql/react-apollo/issues/807.

Hopefully this will also get resolved before v2 is released, since it looks like they are finally giving some attention to this problems.

Are you planning to merge this to `master` or will you wait until `persistgraphql ` gets resolved as well?

**Comment by vlasenko** [comment]
@mitjade I plan to make branch for `apollov1` to let people with projects on Apollo 1 continue using starter kit with Apollo 1, until Apollo 2 will be released officially. After that I plan to merge this PR into master. `master` should always be on the edge. When this happens I think general improvements should be commited both to `apollov1` and to `master` branches until we decide to stop support for Apollo 1

**Comment by mitjade** [comment]
@vlasenko Thx for the info.

**Comment by mairh** [comment]
I believe everything we are supporting in v1 is being supported in v2 as well after this merge?

**Comment by vlasenko** [comment]
@mairh Yes, everything, except persistent GraphQL queries. We are waiting for `persistgraphql` package to support Apollo v2.

**Pull request merged**
