### PR TITLE
disable redux devtool extension in production

### PR DESCRIPTION
**Pull request by zirho**
Just close this if this is not desirable.

### CODE REVIEW

**Comment by vlasenko** [comment]
I agree, it should be disabled during production. @mitjade @mairh Mitja, Ujjwal, what do you guys think?

**Comment by mairh** [comment]
Yes, I never paid attention to this in the kit, but usually, I disable the redux dev tool in all my projects for production use.

**Comment by vlasenko** [comment]
Thank you! Merged

**Comment by vlasenko** [comment]
Great!

**Pull request merged**
