### PR TITLE
Auth refactor

### PR DESCRIPTION
**Pull request by mitjade**
Start of auth refactor

### CODE REVIEW

**Comment by mitjade** [comment]
Still works if `user example deleted`.

**Comment by bastianwegge** [comment]
LGTM
@vlasenko what do you think?

**Comment by vlasenko** [comment]
@bastianwegge I think that build fails

**Comment by mitjade** [comment]
@vlasenko It tests pass on my local machine?

This happened a lot while I developed `auth`.
`Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

**Comment by mitjade** [comment]
@vlasenko What exactly should be added to the docs, regarding login funcionality. Currently we do not explain `counter` or `post` example, but probably should in the future?

**Comment by vlasenko** [comment]
@mitjade `counter' and `post` are more or less self-evident. But auth module is not falling into this category. Thats why I think it should be explained. Nonetheless docs on `counter` and `post` would be nice to have too in the future.

**Comment by mitjade** [comment]
@vlasenko I will open a separate PR for docs, when I have something.

**Comment by vlasenko** [comment]
@mitjade Tests are working now. I have increase timeout for mocha tests from `2s` to `5s`

**Comment by mitjade** [comment]
@bastianwegge Found a few corner cases where my code did not work ok. Had to add back client readable cookies. Also managed to figure out how to sign refresh token with secret and user password.

Is there a way to read page headers in react when initial server rendering is in action? If so I could then get rid of client readable cookies.

**Comment by bastianwegge** [comment]
There's probably a way, take a look at the `server/middleware/html.jsx`. I think helmet is doing something similar on initial rendering (but not sure).

**Comment by vlasenko** [comment]
@mitjade You cannot get headers from initial page request, but you can embed them into the page, like we do for `__APOLLO_STATE__`:
https://github.com/sysgears/apollo-universal-starter-kit/blob/a54b89e7534f8c754a15e45cdf127593c493c8bd/src/server/middleware/html.jsx#L38

**Comment by vlasenko** [comment]
@mitjade But I think using Cookies is fine

**Comment by mitjade** [comment]
Populated `localStorage` tokens on SSR. Without this `localStorage` and `cookies` ware out of sink whenever `cookies `ware refreshed on the server and I could not perform additional checks if `header` and `cookie` tokens are the same.

**Comment by mitjade** [comment]
This is all the time I have. Will try to follow a long while on vacation, but will not do any work, since I promised my wife I will leave my notebook at home :)

**Comment by mitjade** [comment]
I hope this will be useful to people needing `auth` and want to use this kit, if nothing else I got the attention of someone like @bastianwegge that is willing to contribute :)

**Comment by mairh** [comment]
When will you be back @mitjade ?

**Comment by mitjade** [comment]
@mairh In a week, but then I start on a new project and will not have a lot of time to do major work on this kit.

**Comment by vlasenko** [comment]
Awesome work with bringing auth to this kit, Mitja. Have a great vacation time with your wife!

**Comment by vlasenko** [comment]
@mitjade Do you think this PR ready to merge?

**Comment by mitjade** [comment]
@vlasenko Yes. It is better than what is in master.

**Comment by vlasenko** [comment]
Okay, then please go on, merge with squash this PR please

**Comment by mitjade** [comment]
@vlasenko I did a squash merge, but individual commits are still shown in master?

**Comment by vlasenko** [comment]
@mitjade Nope, in the master there is only one commit for this PR

**Pull request merged**
