### PR TITLE
Prettier printWidth 120

### PR DESCRIPTION
**Pull request by mitjade**
I would like to set `printWidth` to 120.

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko Would you agree?

**Comment by mairh** [comment]
I am ok with it. Build is failing though

**Comment by mitjade** [comment]
@vlasenko In my first commit I did not commit any changes to `package.json` or `yarn.lock`, but build failed anyway. Tried to regenerate `yarn.lock` and push again, no difference. I get no error running `yarn test`?

**Comment by vlasenko** [comment]
@mitjade Yes, but Travis logs clearly show that `yarn.lock` is broken. Hashes don't match

**Comment by mitjade** [comment]
@vlasenko Any suggestions how to solve this?

**Comment by vlasenko** [comment]
@mitjade This is not our fault. This is rather fault of module authors. They have replaced library archive with different contents. This will defeat all libraries that use their module and use `yarn.lock`, since hash has changed.

To switch to use new contents of the module `yarn.lock` need to be regenerated. But this cannot be done without clearing yarn cache first. So the recipe to escape from situation like this is:
1. Remove `yarn.lock`
2. Clear Yarn cache: `yarn cache clean`
3. Regenerate `yarn.lock`

**Comment by mitjade** [comment]
@vlasenko Thanks for clearing this up. Will merge this now.

**Pull request merged**
