### PR TITLE
[WIP] SOFA REST API integration

### PR DESCRIPTION
**Pull request by verdverm**
Adds an integration for SOFA REST API, which wraps a graphql schema to provide a REST API

https://medium.com/the-guild/sofa-the-best-way-to-rest-is-graphql-d9da6e8e7693

https://github.com/hofstadter-io/SOFA/pull/1

### CODE REVIEW

**Comment by verdverm** [comment]
still having issues with mutation input being complex types (maybe) and having the POST body and correct inputs making it to mutation resolvers. Trying to causes GraphQL `$input` errors

**Comment by verdverm** [comment]
seems to be working better now!

**Comment by verdverm** [comment]
there are errors on mutually included types

https://github.com/Urigo/SOFA/issues/21

**Comment by verdverm** [comment]
@vlasenko this should be good now, will have to use my fork as I haven't heard back about PRs on the SOFA original

**Comment by vlasenko** [comment]
@verdverm Thank you Tony, I will take it from here

**Pull request merged**
