### PR TITLE
Contact us component

### PR DESCRIPTION
**Pull request by mairh**
- Contact us page component to receive users query/questions.
- The old email account was expired so I have created a new one.

### CODE REVIEW

**Comment by vlasenko** [comment]
Thank you @mairh. Can we make Content field a textarea? Would be great to support attachments too, but this can be left to another PR in the future

**Comment by mairh** [comment]
Good point. It should be `textarea`. I was also thinking about supporting attachments, but then what will happen if someone removes the upload component?

That is why we haven't implemented profile pics upload, adding attachments in the post-comment section.

**Comment by vlasenko** [comment]
Well, I think we can support mechanism for features to announce themselves through connector. For example upload feature can add `upload: true` to the `announcements` object and then `contact` feature can check if `upload` is present in `announcements` and enable or disable attachments based on that?

**Comment by mairh** [comment]
That is one idea - I guess we can do that. Since keeping modularity we are limiting things when it comes about feature-wise. So having a flag for each feature/module and checking if the flag is set to true, we can utilize those modules in another one.

**Comment by mairh** [comment]
@vlasenko Shall we create another PR for profile picture upload and contact us / post-comment attachment addition.

**Comment by vlasenko** [comment]
@mairh Yep, lets do that in separate PRs

**Pull request merged**
