### PR TITLE
Post module refactor

### PR DESCRIPTION
**Pull request by mitjade**
on post add remain on page

### CODE REVIEW

**Comment by mitjade** [comment]
@mairh I managed to combine post add and edit page and create a transition without blinking, for both  web and mobile. Could you take a look, if this is something you intended when we ware discussing this a while back.

I still need to implement nested mutations, so you would be able to add comments before first save, but maybe this is already better to what we have now.

I also plan to add two buttons Save and Save and list to be able to skip one click in case you want to also go back to list..

**Comment by mairh** [comment]
I will have a look tomorrow morning. Thanks for the PR

**Comment by vlasenko** [comment]
@mairh Are you still going to take a look or should we merge this one?

**Comment by mairh** [comment]
I apologize I was too busy to look into it. I will surely review it today and merge it.

**Comment by mitjade** [comment]
@vlasenko I still plan to do some work on this refactoring post example, after I'm done with auth, but in it's current state can already be merged if anyone would find it useful.

**Comment by mairh** [comment]
It looks good. I will merge it

We can take the next 2 points later on when you are done with auth stuff

> Quote 1: I still need to implement nested mutations, so you would be able to add comments before first save, but maybe this is already better to what we have now.

> Quote 2: I also plan to add two buttons Save and Save and list to be able to skip one click in case you want to also go back to list.

**Pull request merged**
