### PR TITLE
Add Apollo Engine support

### PR DESCRIPTION
**Pull request by vlasenko**
Provide integration with Apollo Engine

### CODE REVIEW

**Comment by mitjade** [comment]
You are able to implement this before I was able to read the docs :)

Will test it out now.

**Comment by vlasenko** [comment]
@mitjade Unfortunately it doesn't work for me at the moment....

**Comment by mitjade** [comment]
@vlasenko Yes, it also does not work for me.

**Comment by vlasenko** [comment]
@mitjade I was able to go a little further with Apollo Engine, but I'm having errors about unmarshalling array from queries. Looks like Apollo Engine doesn't support batched queries at the moment? I'm going to submit issue report about this.

**Comment by mitjade** [comment]
@vlasenko Great!

**Pull request merged**
