### PR TITLE
general improvements

### PR DESCRIPTION
**Pull request by mitjade**
- settings for token secret and google analytics
- expose webSocket in in createContext

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko I'm trying to port one of my projects to the latest version of the kit.

Whenever I find I made changes outside of modules, I am typing to modularise this, so future upgrades would be easier.

**Comment by vlasenko** [comment]
@mitjade Sure, sounds good

**Comment by vlasenko** [comment]
Looks good to me

**Comment by mairh** [comment]
Just for my information. What does the secret token actually do in this kit?

**Comment by mitjade** [comment]
@mairh Secret is used to sign tokens on the server. So if someone would want to inject a different token, it would not be valid unless he knows your secret.

**Comment by mairh** [comment]
Why aren't we using it for the prod Heroku demo?

**Comment by mitjade** [comment]
@mairh What do you mean exactly?

**Comment by mairh** [comment]
As far I understand it is used for the user authentication stuff? Or something else?

**Comment by mitjade** [comment]
Yes.

**Comment by mairh** [comment]
How does the secret token is generated? So for example, if I do a prod release I should put some random token there?

**Comment by mitjade** [comment]
Currently you need to do this by your self. That is why on intentionally named it `secret, change for production`.

**Comment by mitjade** [comment]
There are still a lot of improvements to be made to `auth`, to be really useful, but it is a bug task and I do not have the time do really do it all, plus I am not that experienced in this area and am still learning stuff as I go along :)

**Comment by mairh** [comment]
It is already useful at the moment. A good addition I would say! We can keep improving it when using it in real life projects.

**Comment by mitjade** [comment]
@mairh Thx! Thats the plan.

**Pull request merged**
