### PR TITLE
Add multi-package support via Lerna

### PR DESCRIPTION
**Pull request by vlasenko**
This is a work in progress

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko Looks like you are making good progress with this.

**Comment by vlasenko** [comment]
@mitjade Thank you Mitja. I'm going to keep future commits to this branch to have successful builds. At this stage I see way too many rough edges. Hopefully the whole picture will be more clear in a coming week or two.

**Comment by mairh** [comment]
What are the commands / steps to test this branch.

**Comment by vlasenko** [comment]
@mairh 
- `yarn`
- `yarn seed`
- `yarn watch`

**Comment by mairh** [comment]
ah ok. I thought `lerna bootstrap` or something

**Comment by vlasenko** [comment]
@mairh It does `lerna bootstrap` in `postinstall` script of main `package.json` for you

**Comment by mairh** [comment]
Sweet. Now we can run `ios` and `android` at the same time. Awesome job!

**Comment by vlasenko** [comment]
@mairh Yes and we can upgrade Android and iOS to the latest Expo / React Native I think. I might want to try this tomorrow morning, because I'm curious

**Comment by mairh** [comment]
Just with a quick look I noticed some quirks. For e.g we are generating `app.json` in every packages with same same data. Seems a bit confusing

`client/android/app.json`
`client/ios/app.json`
`client/web/app.json`
`server/core/app.json`

**Comment by vlasenko** [comment]
Yes, I'm aware of this. Because `app.json` was used everywhere, I have just copied it into each package. But actually not all fields are used by each package, so some cleanup is needed to actually have only the fields that is used by relevant package in each `app.json`.

**Comment by vlasenko** [comment]
It would be good to also leverage Lerna dependency hoisting, to cut down on initial `yarn` install time, but this might be tricky, because all the tools should support it. I have checked and have got the problems. so this one needs invesitgation

**Comment by vlasenko** [comment]
I have also tried to decouple build infrastructure into separate tool `wiq`. `wiq` tool is responsible for webpack configuration and webpack running, and yet it lets each package tweak actual webpack config the way package needs. This tool should also help generating `package.json` `dependencies` and `devDependencies` so that it was possible to create many more packages for e.g. microservices and prepopullate their dependencies

**Comment by mairh** [comment]
1) Yep. Only having the necessary info in each `app.json` is fine and clear enough.

2) Cutting down the initial `yarn install`time is good to have, but it is not a dead critical priority. We can do it once we have time - No immediate attention needed

3) No idea what is going behind the scene in `wiq` but having the tool folder separated from other packages is good. By the way what is the full form of `wiq`? What it stands for?

**Comment by vlasenko** [comment]
@mairh `wiq` is just a short name that is generally unoccupied by any command line Unix tool yet. But if you want it can stand for `Webpack Interface Queen` :)

**Comment by mairh** [comment]
Just need to find a way to run android emulator on Mac.

`xcode` opens the emulator as usual but I still trying to figure out what emulator should i use to run `android` client on Mac. I tried to follow https://facebook.github.io/react-native/releases/0.23/docs/android-setup.html#install-the-android-sdk-unless-you-already-have-it but I guess out tooling a bit different and we use expo as our middleware that's why the official react-native way didn't work.

I don't wanna pay for `Genymotion` :)

**Comment by vlasenko** [comment]
@mairh These docs are seriously outdated. Right now the easiest way is to install Android Studio and configure virtual phone via `Tools -> Android -> AVD Manager`. Choose Lollipop x86_64 API for your Phone, it is the lowest x86_64 API (because it is x86_64 emulator will work really fast). Make sure that you add `~/Android/Sdk/platform-tools` folder that has `adb` into `PATH` env variable, so that Expo used `adb` instance from Android SDK. 

Then launch your virtual phone and launch starter kit after that. It should all work. It works for me this way even better then with Genymotion

**Comment by mairh** [comment]
I tried setting up Genymotion, but the custom android sdk part was confusing. Anyway, I will try with Android studio

**Comment by mairh** [comment]
I'll try to take notes of every problem I am facing so that we can induce all of those in the online doc.

**Comment by vlasenko** [comment]
Sounds good, thank you Ujjwal!

**Comment by mairh** [comment]
Actually we need to change the readme for Android a little bit. On `osx` Android studio interface is a bit different. There is no `Tools -> Android -> AVD Manager` option.

https://stackoverflow.com/questions/43055787/avd-manager-in-android-studio-mac-osx

**Comment by vlasenko** [comment]
@mairh Feel free to correct it

**Comment by mairh** [comment]
Sure. Let me first get it up and running and I will add the necessary steps

**Comment by mairh** [comment]
Got the Android client to work on oxs :)
screen shot 2017-06-20 at 13 09 08

**Comment by vlasenko** [comment]
Upgraded this branch to Expo 17 for Android and iOS and React 15.6 for Web. Works for me.

**Comment by mairh** [comment]
What's the release plan for this PR? Are you still working on improving this PR?

If you think it is good enough as a first release we can go ahead and merge this in master and improve later on wherever necessary. 

We probably need to write a short migration guide for people who are using the old way of running this kit. As a starter we can just show what to change and how to restructure the code should be enough.

**Comment by vlasenko** [comment]
@mairh It is not yet ready to release I think. PersistGraphQL option is not working, frontendRefreshOnBackendChange is not working. Also installing initial dependencies is considerably slower then on a single-package variant.

**Comment by mairh** [comment]
hmm yeah I guess those are important to fix. At least everything should be supported what we are supporting at the moment.

**Comment by vlasenko** [comment]
Closing as it is seriously outdated now

**Pull request closed without merging**
