### PR TITLE
Send email on add new user with login details

### PR DESCRIPTION
**Pull request by mairh**
Send an email with login details to the user when added or registered.

### CODE REVIEW

**Comment by mitjade** [comment]
@mairh Looks great! Maybe make a function and use it in both places.

**Comment by mairh** [comment]
I think instead of a function we can create an email-template folder and have all the emails in one place. But that will require some refactoring. I guess we can go with the current solution and creating a function wouldn't make things easier for users who would like to change some minor things in the current template.

**Comment by vlasenko** [comment]
Thank you @mairh, looks good!

**Comment by mitjade** [comment]
@mairh Yes, we can deal with this later on.

**Pull request merged**
