### PR TITLE
Ui refactor

### PR DESCRIPTION
**Pull request by mitjade**
Remove unneeded backend module.

`Antd` refactor imports.

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko Is there a way to dynamically change the import in `src/client/modules/common/components/web/index.jsx`?

**Comment by mitjade** [comment]
I would like to write some docs how to switch between supported `UI's` and it would really be cool to be able to make the `UI` switch with just one change.

**Comment by mitjade** [comment]
But even if this remains as is, this way you could load parts of different `UI's` and use more than one. You would need to only load specific parts of css then as well, so common styling do not clash.

**Comment by vlasenko** [comment]
> @vlasenko Is there a way to dynamically change the import in `src/client/modules/common/components/web/index.jsx`?

Yes, webpack support dynamic require syntax, we can utilise it for that purpose

**Comment by mitjade** [comment]
Will read it to it and try to implement it.

**Comment by mitjade** [comment]
@vlasenko Could you give me an example for to accomplish this. I am not able to make this work.

I need for example to import from `../../../ui-[module]/components/PageLayout` and export it as `export { PageLayout }`.

**Comment by mitjade** [comment]
I will just leave it as is, since it only complicates the whole thing and you really do not gain much.

**Pull request merged**
