### PR TITLE
Upgrade to React 16

### PR DESCRIPTION
**Pull request by vlasenko**
This is an early attempt to upgrade the kit to React 16. The full upgrade will be ready when all dependencies are ready for React 16, or when alternatives found for these dependencies.

Enzyme is not ready for React 16, so tests are disabled for now.

### CODE REVIEW

**Comment by vlasenko** [comment]
Web and Mobile part works for me, though more thorough checking is needed. The only thing that is not working is UI tests, due to Enzyme issues

**Comment by mitjade** [comment]
@vlasenko https://github.com/airbnb/enzyme just got updated to `v3.0.0`, that should support `react` `v16`

**Comment by vlasenko** [comment]
@mitjade Many thanks for the hint Mitja! I will check now

**Comment by vlasenko** [comment]
@mitjade Okay, I have tried, it doesn't work for me with React 16. Well it kinda works but have lots of bugs, that makes it usage impractical

**Comment by vlasenko** [comment]
@mitjade So Enzyme v3 has problems with traversing React 16 tree. Except UI tests, everything else works fine in this branch.

**Comment by mitjade** [comment]
@vlasenko Great! Hopefully it will get fixed by the time `react` is released and then you can merge this, or did you plan to do it sooner?

**Comment by vlasenko** [comment]
@mitjade I plan to do this right on the day when React 16 get finally released, if Enzyme will be usable on that date as well.

**Comment by mitjade** [comment]
@vlasenko Sound good.

**Comment by mitjade** [comment]
@vlasenko https://github.com/facebook/react/releases/tag/v16.0.0

**Comment by vlasenko** [comment]
@mitjade Yes, I saw React 16 release. But Enzyme@3 doesn't work for me neither for React 16 nor for React 15.4

**Comment by vlasenko** [comment]
Enzyme 3 is not working properly with React 16 at the moment:
https://github.com/airbnb/enzyme/issues/1163

@mairh @mitjade What should we do? Wait for the fix, or disable UI tests for now and merge this PR?

**Comment by mairh** [comment]
I think if we wait more this PR will go into the stale mode and probably you will end up fixing all other packages based on their future updates. So, I'll say merge this and disable the tests for now.

**Comment by mitjade** [comment]
@vlasenko I agree with @mairh. Let's merge and deal with tests later on.

**Comment by mairh** [comment]
I am sure you have noticed the merge conflicts in this PR.

**Comment by vlasenko** [comment]
@mairh @mitjade I was able to find workarounds for `Counter` UI tests for Enzyme 3. So we have at least one working UI tests example for React 16.

**Pull request merged**
