### PR TITLE
[WIP] Electron Target

### PR DESCRIPTION
**Pull request by verdverm**
https://github.com/sysgears/spinjs/pull/42

### CODE REVIEW

**Comment by vlasenko** [comment]
@verdverm Tony, is work on this is still in progress?

**Comment by verdverm** [comment]
@vlasenko I would like it to be... I meant to ask for your insights on the right way to do this.

thoughts:

1) Most of the changes will be in this repository, while there is a smaller set of modifications to SpinJS.
2) With the current modules / folders layout, the spinrc.json file will need another builder that points to a different entrypoint in the `packages/client` folder. There will likely be a number of files added to this directory to support the ( more complicated ) electron processes.

Does this sound about right?

**Comment by vlasenko** [comment]
@verdverm I think we can have separate folder for electron, e.g. `packages/electron` with setup to build electron and very specific electron-related code, much like we have `packages/mobile` now. Yet the UI components for electron might reside in `packages/client` in files having `.electron.js` extension

**Comment by vlasenko** [comment]
This seem to be stuck, closing it for now, feel free to reopen

**Pull request closed without merging**
