### PR TITLE
Improve user module

### PR DESCRIPTION
**Pull request by mitjade**
Add ability to search, filter and sort users.

Add, edit, delete are still work in progress.

### CODE REVIEW

**Comment by vlasenko** [comment]
Awesome work Mitja! Though I see `console.log` at some places, for debugging purposes I assume. I think we should disable `console.log` in eslint rules, so that they don't penetrate into the kit code, all output should go through logger, and debugging `console.log` shouldn't be commited

**Comment by mitjade** [comment]
@vlasenko Thank you. This is not jet ready to be merged and those console logs will be removed when I implement the missing functionality.

**Comment by mitjade** [comment]
@vlasenko I committed and example on how to do debounce on search field, but I keep getting `_this.doSearch is not a function`? I followed [this](https://github.com/jscomplete/advanced-react/blob/master/lib/components/SearchBar.js) example, but it for some reason does not work for me. Could this be a React 16 breaking change?

Found some reference on StackOverflow to [SyntheticEvent](https://reactjs.org/docs/events.html#event-pooling), but am not sure exactly what am I doing wrong.

If you would have some time to quickly take a look at this, otherwise I will remove this for now, until I figure out what I am doing wrong.

**Comment by vlasenko** [comment]
@mitjade I think its React 16  specific issue. Lets remove it for now and examine later.

**Comment by mitjade** [comment]
OK

**Comment by mitjade** [comment]
Debounce now working.
Delete user with handled errors.

**Comment by vlasenko** [comment]
Awesome!

**Comment by mitjade** [comment]
Still missing and intend to add before merging:
- add and edit user in users page
- edit on profile page (username and password)

**Comment by mitjade** [comment]
There was an issue with `sqlite`, that foreign key constraints ware not working correctly. Fixed as proposed in this [issue](https://github.com/tgriesser/knex/issues/453).

**Comment by mitjade** [comment]
@vlasenko I think this is now good enough to be included in the kit. Lot's of things that could still be improved, but I would like to focus now on some other parts first.

**Comment by vlasenko** [comment]
@mitjade Please go forward and merge, I trust your judgement.

**Comment by vlasenko** [comment]
@mitjade I have checked this right now. This is a great addition to our existing examples from several angles of view, awesome work, as always, Mitja!

**Pull request merged**
