### PR TITLE
Extract UI components into common module

### PR DESCRIPTION
**Pull request by mitjade**
Initial try to extract button component into common module (not working)

### CODE REVIEW

**Comment by mitjade** [comment]
@vlasenko I would like to tackle the last major thing that causes a lot of merge conflicts for me.

I would like to extract all UI specific components into `modules/common`, like we have now for `react-native` for `buttons`. This way you would have all UI specific stuff in one module and only have to rewrite this, to switch to a new UI like `material design`, `semantic-ui`, `antd`, etc...

But currently if I include `Button` component in my web components like `import { Button } from '../../common/components';`, it seems to also wants to load `react-native` components. I have to comment out all `react-native` components for this to work.

If I include `Button` like `import Button from '../../common/components/Button';` it all works ok.

Aly idea how to fix this? You can see my attempt of this in `counter` example.

**Comment by vlasenko** [comment]
@mitjade I'm not sure I understand the problem. Web front-end will load `react-native-web` components, and what is the problem with this?

**Comment by vlasenko** [comment]
@mitjade If there some non react-native-web components, their files should clearly state that - they need to have `.native.js` extension if they are `react-native`-only components

**Comment by mitjade** [comment]
@vlasenko Thank you for the hint. I was using `react-naitive` specific code in a component that did not have `.naitive.jsx` suffix.

**Comment by vlasenko** [comment]
@mitjade Yes, sounds good. Lets make antd example to master

**Comment by mitjade** [comment]
@vlasenko This PR is now almost ready. Some changes needed for `antd`, but since `bootstrap` is set by default, this could be done later. Also it is still not yet 100% react 16 compatible.

There are quite a lot of changes needed to be made, but I think it will be worth it in the long run. Now if you want to switch from `bootstrap` to `antd`, all you need to do, is some minor changes in `src/client/modules/index.js`, `src/server/modules/index.js` and `src/client/modules/common/components/web/index.jsx`. I'm sure this could be optimised, but I guess it is good enough for the start.

To switch to something like `semantic-ui`, that is not yet implemented, you need to copy `ui-bootstrap` components and reimplement them in `ui-semantic` module. I think this should take less than one hour and you do not need to change one file in any of the other modules to archive this. Similarly `NativeBase` could be implemented now for `react-native`.

This structure in `common` modules is setup now in a way that you can add `universal`, `native` or `web` components. There is some more work to set this up, but in this way, moving components around and using different `ui` packages, would make this easier to achieve. 

With this, I now addressed all points I made in #389, with the files that caused me merge conflicts.

**Pull request merged**
